title: Resilience Planning for Maryland Defense Communities
email: lmantel@umaryland.edu
description: >-
  A statewide convening focused on resilience planning for Maryland defense communities.
baseurl: ""
url: "https://mdresilienceconvening.org"
registration_url: "https://forms.office.com/pages/responsepage.aspx?id=SrzNPUx-e0CA93-2dXGC8gIwtAkJ4cVKkAZkzsZv6lpUOFhEMDBFWTE0VE5XUUFBWE9XWERMUjI0OC4u&route=shorturl"

markdown: kramdown
permalink: pretty

theme: null
plugins: []
